#include "llvm.h"

LLVM_API int AbortProcessAction() { return LLVMAbortProcessAction; }
LLVM_API int PrintMessageAction() { return LLVMPrintMessageAction; }
LLVM_API int ReturnStatusAction() { return LLVMReturnStatusAction; }
LLVM_API int AnyComdatSelectionKind() { return LLVMAnyComdatSelectionKind; }
LLVM_API int ExactMatchComdatSelectionKind() { return LLVMExactMatchComdatSelectionKind; }
LLVM_API int LargestComdatSelectionKind() { return LLVMLargestComdatSelectionKind; }
LLVM_API int NoDuplicatesComdatSelectionKind() { return LLVMNoDuplicatesComdatSelectionKind; }
LLVM_API int SameSizeComdatSelectionKind() { return LLVMSameSizeComdatSelectionKind; }
LLVM_API int Ret() { return LLVMRet; }
LLVM_API int Br() { return LLVMBr; }
LLVM_API int Switch() { return LLVMSwitch; }
LLVM_API int IndirectBr() { return LLVMIndirectBr; }
LLVM_API int Invoke() { return LLVMInvoke; }
LLVM_API int Unreachable() { return LLVMUnreachable; }
LLVM_API int CallBr() { return LLVMCallBr; }
LLVM_API int FNeg() { return LLVMFNeg; }
LLVM_API int Add() { return LLVMAdd; }
LLVM_API int FAdd() { return LLVMFAdd; }
LLVM_API int Sub() { return LLVMSub; }
LLVM_API int FSub() { return LLVMFSub; }
LLVM_API int Mul() { return LLVMMul; }
LLVM_API int FMul() { return LLVMFMul; }
LLVM_API int UDiv() { return LLVMUDiv; }
LLVM_API int SDiv() { return LLVMSDiv; }
LLVM_API int FDiv() { return LLVMFDiv; }
LLVM_API int URem() { return LLVMURem; }
LLVM_API int SRem() { return LLVMSRem; }
LLVM_API int FRem() { return LLVMFRem; }
LLVM_API int Shl() { return LLVMShl; }
LLVM_API int LShr() { return LLVMLShr; }
LLVM_API int AShr() { return LLVMAShr; }
LLVM_API int And() { return LLVMAnd; }
LLVM_API int Or() { return LLVMOr; }
LLVM_API int Xor() { return LLVMXor; }
LLVM_API int Alloca() { return LLVMAlloca; }
LLVM_API int Load() { return LLVMLoad; }
LLVM_API int Store() { return LLVMStore; }
LLVM_API int GetElementPtr() { return LLVMGetElementPtr; }
LLVM_API int Trunc() { return LLVMTrunc; }
LLVM_API int ZExt() { return LLVMZExt; }
LLVM_API int SExt() { return LLVMSExt; }
LLVM_API int FPToUI() { return LLVMFPToUI; }
LLVM_API int FPToSI() { return LLVMFPToSI; }
LLVM_API int UIToFP() { return LLVMUIToFP; }
LLVM_API int SIToFP() { return LLVMSIToFP; }
LLVM_API int FPTrunc() { return LLVMFPTrunc; }
LLVM_API int FPExt() { return LLVMFPExt; }
LLVM_API int PtrToInt() { return LLVMPtrToInt; }
LLVM_API int IntToPtr() { return LLVMIntToPtr; }
LLVM_API int BitCast() { return LLVMBitCast; }
LLVM_API int AddrSpaceCast() { return LLVMAddrSpaceCast; }
LLVM_API int ICmp() { return LLVMICmp; }
LLVM_API int FCmp() { return LLVMFCmp; }
LLVM_API int PHI() { return LLVMPHI; }
LLVM_API int Call() { return LLVMCall; }
LLVM_API int Select() { return LLVMSelect; }
LLVM_API int UserOp1() { return LLVMUserOp1; }
LLVM_API int UserOp2() { return LLVMUserOp2; }
LLVM_API int VAArg() { return LLVMVAArg; }
LLVM_API int ExtractElement() { return LLVMExtractElement; }
LLVM_API int InsertElement() { return LLVMInsertElement; }
LLVM_API int ShuffleVector() { return LLVMShuffleVector; }
LLVM_API int ExtractValue() { return LLVMExtractValue; }
LLVM_API int InsertValue() { return LLVMInsertValue; }
LLVM_API int Freeze() { return LLVMFreeze; }
LLVM_API int Fence() { return LLVMFence; }
LLVM_API int AtomicCmpXchg() { return LLVMAtomicCmpXchg; }
LLVM_API int AtomicRMW() { return LLVMAtomicRMW; }
LLVM_API int Resume() { return LLVMResume; }
LLVM_API int LandingPad() { return LLVMLandingPad; }
LLVM_API int CleanupRet() { return LLVMCleanupRet; }
LLVM_API int CatchRet() { return LLVMCatchRet; }
LLVM_API int CatchPad() { return LLVMCatchPad; }
LLVM_API int CleanupPad() { return LLVMCleanupPad; }
LLVM_API int CatchSwitch() { return LLVMCatchSwitch; }
LLVM_API int VoidTypeKind() { return LLVMVoidTypeKind; }
LLVM_API int HalfTypeKind() { return LLVMHalfTypeKind; }
LLVM_API int FloatTypeKind() { return LLVMFloatTypeKind; }
LLVM_API int DoubleTypeKind() { return LLVMDoubleTypeKind; }
LLVM_API int X86_FP80TypeKind() { return LLVMX86_FP80TypeKind; }
LLVM_API int FP128TypeKind() { return LLVMFP128TypeKind; }
LLVM_API int PPC_FP128TypeKind() { return LLVMPPC_FP128TypeKind; }
LLVM_API int LabelTypeKind() { return LLVMLabelTypeKind; }
LLVM_API int IntegerTypeKind() { return LLVMIntegerTypeKind; }
LLVM_API int FunctionTypeKind() { return LLVMFunctionTypeKind; }
LLVM_API int StructTypeKind() { return LLVMStructTypeKind; }
LLVM_API int ArrayTypeKind() { return LLVMArrayTypeKind; }
LLVM_API int PointerTypeKind() { return LLVMPointerTypeKind; }
LLVM_API int VectorTypeKind() { return LLVMVectorTypeKind; }
LLVM_API int MetadataTypeKind() { return LLVMMetadataTypeKind; }
LLVM_API int X86_MMXTypeKind() { return LLVMX86_MMXTypeKind; }
LLVM_API int TokenTypeKind() { return LLVMTokenTypeKind; }
LLVM_API int ExternalLinkage() { return LLVMExternalLinkage; }
LLVM_API int AvailableExternallyLinkage() { return LLVMAvailableExternallyLinkage; }
LLVM_API int LinkOnceAnyLinkage() { return LLVMLinkOnceAnyLinkage; }
LLVM_API int LinkOnceODRLinkage() { return LLVMLinkOnceODRLinkage; }
LLVM_API int LinkOnceODRAutoHideLinkage() { return LLVMLinkOnceODRAutoHideLinkage; }
LLVM_API int WeakAnyLinkage() { return LLVMWeakAnyLinkage; }
LLVM_API int WeakODRLinkage() { return LLVMWeakODRLinkage; }
LLVM_API int AppendingLinkage() { return LLVMAppendingLinkage; }
LLVM_API int InternalLinkage() { return LLVMInternalLinkage; }
LLVM_API int PrivateLinkage() { return LLVMPrivateLinkage; }
LLVM_API int DLLImportLinkage() { return LLVMDLLImportLinkage; }
LLVM_API int DLLExportLinkage() { return LLVMDLLExportLinkage; }
LLVM_API int ExternalWeakLinkage() { return LLVMExternalWeakLinkage; }
LLVM_API int GhostLinkage() { return LLVMGhostLinkage; }
LLVM_API int CommonLinkage() { return LLVMCommonLinkage; }
LLVM_API int LinkerPrivateLinkage() { return LLVMLinkerPrivateLinkage; }
LLVM_API int LinkerPrivateWeakLinkage() { return LLVMLinkerPrivateWeakLinkage; }
LLVM_API int DefaultVisibility() { return LLVMDefaultVisibility; }
LLVM_API int HiddenVisibility() { return LLVMHiddenVisibility; }
LLVM_API int ProtectedVisibility() { return LLVMProtectedVisibility; }
LLVM_API int NoUnnamedAddr() { return LLVMNoUnnamedAddr; }
LLVM_API int LocalUnnamedAddr() { return LLVMLocalUnnamedAddr; }
LLVM_API int GlobalUnnamedAddr() { return LLVMGlobalUnnamedAddr; }
LLVM_API int DefaultStorageClass() { return LLVMDefaultStorageClass; }
LLVM_API int DLLImportStorageClass() { return LLVMDLLImportStorageClass; }
LLVM_API int DLLExportStorageClass() { return LLVMDLLExportStorageClass; }
LLVM_API int CCallConv() { return LLVMCCallConv; }
LLVM_API int FastCallConv() { return LLVMFastCallConv; }
LLVM_API int ColdCallConv() { return LLVMColdCallConv; }
LLVM_API int GHCCallConv() { return LLVMGHCCallConv; }
LLVM_API int HiPECallConv() { return LLVMHiPECallConv; }
LLVM_API int WebKitJSCallConv() { return LLVMWebKitJSCallConv; }
LLVM_API int AnyRegCallConv() { return LLVMAnyRegCallConv; }
LLVM_API int PreserveMostCallConv() { return LLVMPreserveMostCallConv; }
LLVM_API int PreserveAllCallConv() { return LLVMPreserveAllCallConv; }
LLVM_API int SwiftCallConv() { return LLVMSwiftCallConv; }
LLVM_API int CXXFASTTLSCallConv() { return LLVMCXXFASTTLSCallConv; }
LLVM_API int X86StdcallCallConv() { return LLVMX86StdcallCallConv; }
LLVM_API int X86FastcallCallConv() { return LLVMX86FastcallCallConv; }
LLVM_API int ARMAPCSCallConv() { return LLVMARMAPCSCallConv; }
LLVM_API int ARMAAPCSCallConv() { return LLVMARMAAPCSCallConv; }
LLVM_API int ARMAAPCSVFPCallConv() { return LLVMARMAAPCSVFPCallConv; }
LLVM_API int MSP430INTRCallConv() { return LLVMMSP430INTRCallConv; }
LLVM_API int X86ThisCallCallConv() { return LLVMX86ThisCallCallConv; }
LLVM_API int PTXKernelCallConv() { return LLVMPTXKernelCallConv; }
LLVM_API int PTXDeviceCallConv() { return LLVMPTXDeviceCallConv; }
LLVM_API int SPIRFUNCCallConv() { return LLVMSPIRFUNCCallConv; }
LLVM_API int SPIRKERNELCallConv() { return LLVMSPIRKERNELCallConv; }
LLVM_API int IntelOCLBICallConv() { return LLVMIntelOCLBICallConv; }
LLVM_API int X8664SysVCallConv() { return LLVMX8664SysVCallConv; }
LLVM_API int Win64CallConv() { return LLVMWin64CallConv; }
LLVM_API int X86VectorCallCallConv() { return LLVMX86VectorCallCallConv; }
LLVM_API int HHVMCallConv() { return LLVMHHVMCallConv; }
LLVM_API int HHVMCCallConv() { return LLVMHHVMCCallConv; }
LLVM_API int X86INTRCallConv() { return LLVMX86INTRCallConv; }
LLVM_API int AVRINTRCallConv() { return LLVMAVRINTRCallConv; }
LLVM_API int AVRSIGNALCallConv() { return LLVMAVRSIGNALCallConv; }
LLVM_API int AVRBUILTINCallConv() { return LLVMAVRBUILTINCallConv; }
LLVM_API int AMDGPUVSCallConv() { return LLVMAMDGPUVSCallConv; }
LLVM_API int AMDGPUGSCallConv() { return LLVMAMDGPUGSCallConv; }
LLVM_API int AMDGPUPSCallConv() { return LLVMAMDGPUPSCallConv; }
LLVM_API int AMDGPUCSCallConv() { return LLVMAMDGPUCSCallConv; }
LLVM_API int AMDGPUKERNELCallConv() { return LLVMAMDGPUKERNELCallConv; }
LLVM_API int X86RegCallCallConv() { return LLVMX86RegCallCallConv; }
LLVM_API int AMDGPUHSCallConv() { return LLVMAMDGPUHSCallConv; }
LLVM_API int MSP430BUILTINCallConv() { return LLVMMSP430BUILTINCallConv; }
LLVM_API int AMDGPULSCallConv() { return LLVMAMDGPULSCallConv; }
LLVM_API int AMDGPUESCallConv() { return LLVMAMDGPUESCallConv; }
LLVM_API int ArgumentValueKind() { return LLVMArgumentValueKind; }
LLVM_API int BasicBlockValueKind() { return LLVMBasicBlockValueKind; }
LLVM_API int MemoryUseValueKind() { return LLVMMemoryUseValueKind; }
LLVM_API int MemoryDefValueKind() { return LLVMMemoryDefValueKind; }
LLVM_API int MemoryPhiValueKind() { return LLVMMemoryPhiValueKind; }
LLVM_API int FunctionValueKind() { return LLVMFunctionValueKind; }
LLVM_API int GlobalAliasValueKind() { return LLVMGlobalAliasValueKind; }
LLVM_API int GlobalIFuncValueKind() { return LLVMGlobalIFuncValueKind; }
LLVM_API int GlobalVariableValueKind() { return LLVMGlobalVariableValueKind; }
LLVM_API int BlockAddressValueKind() { return LLVMBlockAddressValueKind; }
LLVM_API int ConstantExprValueKind() { return LLVMConstantExprValueKind; }
LLVM_API int ConstantArrayValueKind() { return LLVMConstantArrayValueKind; }
LLVM_API int ConstantStructValueKind() { return LLVMConstantStructValueKind; }
LLVM_API int ConstantVectorValueKind() { return LLVMConstantVectorValueKind; }
LLVM_API int UndefValueValueKind() { return LLVMUndefValueValueKind; }
LLVM_API int ConstantAggregateZeroValueKind() { return LLVMConstantAggregateZeroValueKind; }
LLVM_API int ConstantDataArrayValueKind() { return LLVMConstantDataArrayValueKind; }
LLVM_API int ConstantDataVectorValueKind() { return LLVMConstantDataVectorValueKind; }
LLVM_API int ConstantIntValueKind() { return LLVMConstantIntValueKind; }
LLVM_API int ConstantFPValueKind() { return LLVMConstantFPValueKind; }
LLVM_API int ConstantPointerNullValueKind() { return LLVMConstantPointerNullValueKind; }
LLVM_API int ConstantTokenNoneValueKind() { return LLVMConstantTokenNoneValueKind; }
LLVM_API int MetadataAsValueValueKind() { return LLVMMetadataAsValueValueKind; }
LLVM_API int InlineAsmValueKind() { return LLVMInlineAsmValueKind; }
LLVM_API int InstructionValueKind() { return LLVMInstructionValueKind; }
LLVM_API int IntEQ() { return LLVMIntEQ; }
LLVM_API int IntNE() { return LLVMIntNE; }
LLVM_API int IntUGT() { return LLVMIntUGT; }
LLVM_API int IntUGE() { return LLVMIntUGE; }
LLVM_API int IntULT() { return LLVMIntULT; }
LLVM_API int IntULE() { return LLVMIntULE; }
LLVM_API int IntSGT() { return LLVMIntSGT; }
LLVM_API int IntSGE() { return LLVMIntSGE; }
LLVM_API int IntSLT() { return LLVMIntSLT; }
LLVM_API int IntSLE() { return LLVMIntSLE; }
LLVM_API int RealPredicateFalse() { return LLVMRealPredicateFalse; }
LLVM_API int RealOEQ() { return LLVMRealOEQ; }
LLVM_API int RealOGT() { return LLVMRealOGT; }
LLVM_API int RealOGE() { return LLVMRealOGE; }
LLVM_API int RealOLT() { return LLVMRealOLT; }
LLVM_API int RealOLE() { return LLVMRealOLE; }
LLVM_API int RealONE() { return LLVMRealONE; }
LLVM_API int RealORD() { return LLVMRealORD; }
LLVM_API int RealUNO() { return LLVMRealUNO; }
LLVM_API int RealUEQ() { return LLVMRealUEQ; }
LLVM_API int RealUGT() { return LLVMRealUGT; }
LLVM_API int RealUGE() { return LLVMRealUGE; }
LLVM_API int RealULT() { return LLVMRealULT; }
LLVM_API int RealULE() { return LLVMRealULE; }
LLVM_API int RealUNE() { return LLVMRealUNE; }
LLVM_API int RealPredicateTrue() { return LLVMRealPredicateTrue; }
LLVM_API int LandingPadCatch() { return LLVMLandingPadCatch; }
LLVM_API int LandingPadFilter() { return LLVMLandingPadFilter; }
LLVM_API int NotThreadLocal() { return LLVMNotThreadLocal; }
LLVM_API int GeneralDynamicTLSModel() { return LLVMGeneralDynamicTLSModel; }
LLVM_API int LocalDynamicTLSModel() { return LLVMLocalDynamicTLSModel; }
LLVM_API int InitialExecTLSModel() { return LLVMInitialExecTLSModel; }
LLVM_API int LocalExecTLSModel() { return LLVMLocalExecTLSModel; }
LLVM_API int AtomicOrderingNotAtomic() { return LLVMAtomicOrderingNotAtomic; }
LLVM_API int AtomicOrderingUnordered() { return LLVMAtomicOrderingUnordered; }
LLVM_API int AtomicOrderingMonotonic() { return LLVMAtomicOrderingMonotonic; }
LLVM_API int AtomicOrderingAcquire() { return LLVMAtomicOrderingAcquire; }
LLVM_API int AtomicOrderingRelease() { return LLVMAtomicOrderingRelease; }
LLVM_API int AtomicOrderingAcquireRelease() { return LLVMAtomicOrderingAcquireRelease; }
LLVM_API int AtomicOrderingSequentiallyConsistent() { return LLVMAtomicOrderingSequentiallyConsistent; }
LLVM_API int AtomicRMWBinOpXchg() { return LLVMAtomicRMWBinOpXchg; }
LLVM_API int AtomicRMWBinOpAdd() { return LLVMAtomicRMWBinOpAdd; }
LLVM_API int AtomicRMWBinOpSub() { return LLVMAtomicRMWBinOpSub; }
LLVM_API int AtomicRMWBinOpAnd() { return LLVMAtomicRMWBinOpAnd; }
LLVM_API int AtomicRMWBinOpNand() { return LLVMAtomicRMWBinOpNand; }
LLVM_API int AtomicRMWBinOpOr() { return LLVMAtomicRMWBinOpOr; }
LLVM_API int AtomicRMWBinOpXor() { return LLVMAtomicRMWBinOpXor; }
LLVM_API int AtomicRMWBinOpMax() { return LLVMAtomicRMWBinOpMax; }
LLVM_API int AtomicRMWBinOpMin() { return LLVMAtomicRMWBinOpMin; }
LLVM_API int AtomicRMWBinOpUMax() { return LLVMAtomicRMWBinOpUMax; }
LLVM_API int AtomicRMWBinOpUMin() { return LLVMAtomicRMWBinOpUMin; }
LLVM_API int AtomicRMWBinOpFAdd() { return LLVMAtomicRMWBinOpFAdd; }
LLVM_API int AtomicRMWBinOpFSub() { return LLVMAtomicRMWBinOpFSub; }
LLVM_API int DSError() { return LLVMDSError; }
LLVM_API int DSWarning() { return LLVMDSWarning; }
LLVM_API int DSRemark() { return LLVMDSRemark; }
LLVM_API int DSNote() { return LLVMDSNote; }
LLVM_API int InlineAsmDialectATT() { return LLVMInlineAsmDialectATT; }
LLVM_API int InlineAsmDialectIntel() { return LLVMInlineAsmDialectIntel; }
LLVM_API int ModuleFlagBehaviorError() { return LLVMModuleFlagBehaviorError; }
LLVM_API int ModuleFlagBehaviorWarning() { return LLVMModuleFlagBehaviorWarning; }
LLVM_API int ModuleFlagBehaviorRequire() { return LLVMModuleFlagBehaviorRequire; }
LLVM_API int ModuleFlagBehaviorOverride() { return LLVMModuleFlagBehaviorOverride; }
LLVM_API int ModuleFlagBehaviorAppend() { return LLVMModuleFlagBehaviorAppend; }
LLVM_API int ModuleFlagBehaviorAppendUnique() { return LLVMModuleFlagBehaviorAppendUnique; }
LLVM_API int DIFlagZero() { return LLVMDIFlagZero; }
LLVM_API int DIFlagPrivate() { return LLVMDIFlagPrivate; }
LLVM_API int DIFlagProtected() { return LLVMDIFlagProtected; }
LLVM_API int DIFlagPublic() { return LLVMDIFlagPublic; }
LLVM_API int DIFlagFwdDecl() { return LLVMDIFlagFwdDecl; }
LLVM_API int DIFlagAppleBlock() { return LLVMDIFlagAppleBlock; }
LLVM_API int DIFlagReservedBit4() { return LLVMDIFlagReservedBit4; }
LLVM_API int DIFlagVirtual() { return LLVMDIFlagVirtual; }
LLVM_API int DIFlagArtificial() { return LLVMDIFlagArtificial; }
LLVM_API int DIFlagExplicit() { return LLVMDIFlagExplicit; }
LLVM_API int DIFlagPrototyped() { return LLVMDIFlagPrototyped; }
LLVM_API int DIFlagObjcClassComplete() { return LLVMDIFlagObjcClassComplete; }
LLVM_API int DIFlagObjectPointer() { return LLVMDIFlagObjectPointer; }
LLVM_API int DIFlagVector() { return LLVMDIFlagVector; }
LLVM_API int DIFlagStaticMember() { return LLVMDIFlagStaticMember; }
LLVM_API int DIFlagLValueReference() { return LLVMDIFlagLValueReference; }
LLVM_API int DIFlagRValueReference() { return LLVMDIFlagRValueReference; }
LLVM_API int DIFlagReserved() { return LLVMDIFlagReserved; }
LLVM_API int DIFlagSingleInheritance() { return LLVMDIFlagSingleInheritance; }
LLVM_API int DIFlagMultipleInheritance() { return LLVMDIFlagMultipleInheritance; }
LLVM_API int DIFlagVirtualInheritance() { return LLVMDIFlagVirtualInheritance; }
LLVM_API int DIFlagIntroducedVirtual() { return LLVMDIFlagIntroducedVirtual; }
LLVM_API int DIFlagBitField() { return LLVMDIFlagBitField; }
LLVM_API int DIFlagNoReturn() { return LLVMDIFlagNoReturn; }
LLVM_API int DIFlagTypePassByValue() { return LLVMDIFlagTypePassByValue; }
LLVM_API int DIFlagTypePassByReference() { return LLVMDIFlagTypePassByReference; }
LLVM_API int DIFlagEnumClass() { return LLVMDIFlagEnumClass; }
LLVM_API int DIFlagFixedEnum() { return LLVMDIFlagFixedEnum; }
LLVM_API int DIFlagThunk() { return LLVMDIFlagThunk; }
LLVM_API int DIFlagNonTrivial() { return LLVMDIFlagNonTrivial; }
LLVM_API int DIFlagBigEndian() { return LLVMDIFlagBigEndian; }
LLVM_API int DIFlagLittleEndian() { return LLVMDIFlagLittleEndian; }
LLVM_API int DIFlagIndirectVirtualBase() { return LLVMDIFlagIndirectVirtualBase; }
LLVM_API int DIFlagAccessibility() { return LLVMDIFlagAccessibility; }
LLVM_API int DIFlagPtrToMemberRep() { return LLVMDIFlagPtrToMemberRep; }
LLVM_API int DWARFSourceLanguageC89() { return LLVMDWARFSourceLanguageC89; }
LLVM_API int DWARFSourceLanguageC() { return LLVMDWARFSourceLanguageC; }
LLVM_API int DWARFSourceLanguageAda83() { return LLVMDWARFSourceLanguageAda83; }
LLVM_API int DWARFSourceLanguageC_plus_plus() { return LLVMDWARFSourceLanguageC_plus_plus; }
LLVM_API int DWARFSourceLanguageCobol74() { return LLVMDWARFSourceLanguageCobol74; }
LLVM_API int DWARFSourceLanguageCobol85() { return LLVMDWARFSourceLanguageCobol85; }
LLVM_API int DWARFSourceLanguageFortran77() { return LLVMDWARFSourceLanguageFortran77; }
LLVM_API int DWARFSourceLanguageFortran90() { return LLVMDWARFSourceLanguageFortran90; }
LLVM_API int DWARFSourceLanguagePascal83() { return LLVMDWARFSourceLanguagePascal83; }
LLVM_API int DWARFSourceLanguageModula2() { return LLVMDWARFSourceLanguageModula2; }
LLVM_API int DWARFSourceLanguageJava() { return LLVMDWARFSourceLanguageJava; }
LLVM_API int DWARFSourceLanguageC99() { return LLVMDWARFSourceLanguageC99; }
LLVM_API int DWARFSourceLanguageAda95() { return LLVMDWARFSourceLanguageAda95; }
LLVM_API int DWARFSourceLanguageFortran95() { return LLVMDWARFSourceLanguageFortran95; }
LLVM_API int DWARFSourceLanguagePLI() { return LLVMDWARFSourceLanguagePLI; }
LLVM_API int DWARFSourceLanguageObjC() { return LLVMDWARFSourceLanguageObjC; }
LLVM_API int DWARFSourceLanguageObjC_plus_plus() { return LLVMDWARFSourceLanguageObjC_plus_plus; }
LLVM_API int DWARFSourceLanguageUPC() { return LLVMDWARFSourceLanguageUPC; }
LLVM_API int DWARFSourceLanguageD() { return LLVMDWARFSourceLanguageD; }
LLVM_API int DWARFSourceLanguagePython() { return LLVMDWARFSourceLanguagePython; }
LLVM_API int DWARFSourceLanguageOpenCL() { return LLVMDWARFSourceLanguageOpenCL; }
LLVM_API int DWARFSourceLanguageGo() { return LLVMDWARFSourceLanguageGo; }
LLVM_API int DWARFSourceLanguageModula3() { return LLVMDWARFSourceLanguageModula3; }
LLVM_API int DWARFSourceLanguageHaskell() { return LLVMDWARFSourceLanguageHaskell; }
LLVM_API int DWARFSourceLanguageC_plus_plus_03() { return LLVMDWARFSourceLanguageC_plus_plus_03; }
LLVM_API int DWARFSourceLanguageC_plus_plus_11() { return LLVMDWARFSourceLanguageC_plus_plus_11; }
LLVM_API int DWARFSourceLanguageOCaml() { return LLVMDWARFSourceLanguageOCaml; }
LLVM_API int DWARFSourceLanguageRust() { return LLVMDWARFSourceLanguageRust; }
LLVM_API int DWARFSourceLanguageC11() { return LLVMDWARFSourceLanguageC11; }
LLVM_API int DWARFSourceLanguageSwift() { return LLVMDWARFSourceLanguageSwift; }
LLVM_API int DWARFSourceLanguageJulia() { return LLVMDWARFSourceLanguageJulia; }
LLVM_API int DWARFSourceLanguageDylan() { return LLVMDWARFSourceLanguageDylan; }
LLVM_API int DWARFSourceLanguageC_plus_plus_14() { return LLVMDWARFSourceLanguageC_plus_plus_14; }
LLVM_API int DWARFSourceLanguageFortran03() { return LLVMDWARFSourceLanguageFortran03; }
LLVM_API int DWARFSourceLanguageFortran08() { return LLVMDWARFSourceLanguageFortran08; }
LLVM_API int DWARFSourceLanguageRenderScript() { return LLVMDWARFSourceLanguageRenderScript; }
LLVM_API int DWARFSourceLanguageBLISS() { return LLVMDWARFSourceLanguageBLISS; }
LLVM_API int DWARFSourceLanguageMips_Assembler() { return LLVMDWARFSourceLanguageMips_Assembler; }
LLVM_API int DWARFSourceLanguageGOOGLE_RenderScript() { return LLVMDWARFSourceLanguageGOOGLE_RenderScript; }
LLVM_API int DWARFSourceLanguageBORLAND_Delphi() { return LLVMDWARFSourceLanguageBORLAND_Delphi; }
LLVM_API int DWARFEmissionNone() { return LLVMDWARFEmissionNone; }
LLVM_API int DWARFEmissionFull() { return LLVMDWARFEmissionFull; }
LLVM_API int DWARFEmissionLineTablesOnly() { return LLVMDWARFEmissionLineTablesOnly; }
LLVM_API int DWARFMacinfoRecordTypeDefine() { return LLVMDWARFMacinfoRecordTypeDefine; }
LLVM_API int DWARFMacinfoRecordTypeMacro() { return LLVMDWARFMacinfoRecordTypeMacro; }
LLVM_API int DWARFMacinfoRecordTypeStartFile() { return LLVMDWARFMacinfoRecordTypeStartFile; }
LLVM_API int DWARFMacinfoRecordTypeEndFile() { return LLVMDWARFMacinfoRecordTypeEndFile; }
LLVM_API int DWARFMacinfoRecordTypeVendorExt() { return LLVMDWARFMacinfoRecordTypeVendorExt; }
LLVM_API int LinkerDestroySource() { return LLVMLinkerDestroySource; }
LLVM_API int LinkerPreserveSource_Removed() { return LLVMLinkerPreserveSource_Removed; }
LLVM_API int BinaryTypeArchive() { return LLVMBinaryTypeArchive; }
LLVM_API int BinaryTypeMachOUniversalBinary() { return LLVMBinaryTypeMachOUniversalBinary; }
LLVM_API int BinaryTypeCOFFImportFile() { return LLVMBinaryTypeCOFFImportFile; }
LLVM_API int BinaryTypeIR() { return LLVMBinaryTypeIR; }
LLVM_API int BinaryTypeWinRes() { return LLVMBinaryTypeWinRes; }
LLVM_API int BinaryTypeCOFF() { return LLVMBinaryTypeCOFF; }
LLVM_API int BinaryTypeELF32L() { return LLVMBinaryTypeELF32L; }
LLVM_API int BinaryTypeELF32B() { return LLVMBinaryTypeELF32B; }
LLVM_API int BinaryTypeELF64L() { return LLVMBinaryTypeELF64L; }
LLVM_API int BinaryTypeELF64B() { return LLVMBinaryTypeELF64B; }
LLVM_API int BinaryTypeMachO32L() { return LLVMBinaryTypeMachO32L; }
LLVM_API int BinaryTypeMachO32B() { return LLVMBinaryTypeMachO32B; }
LLVM_API int BinaryTypeMachO64L() { return LLVMBinaryTypeMachO64L; }
LLVM_API int BinaryTypeMachO64B() { return LLVMBinaryTypeMachO64B; }
LLVM_API int BinaryTypeWasm() { return LLVMBinaryTypeWasm; }
LLVM_API int CodeGenLevelNone() { return LLVMCodeGenLevelNone; }
LLVM_API int CodeGenLevelLess() { return LLVMCodeGenLevelLess; }
LLVM_API int CodeGenLevelDefault() { return LLVMCodeGenLevelDefault; }
LLVM_API int CodeGenLevelAggressive() { return LLVMCodeGenLevelAggressive; }
LLVM_API int RelocDefault() { return LLVMRelocDefault; }
LLVM_API int RelocStatic() { return LLVMRelocStatic; }
LLVM_API int RelocPIC() { return LLVMRelocPIC; }
LLVM_API int RelocDynamicNoPic() { return LLVMRelocDynamicNoPic; }
LLVM_API int RelocROPI() { return LLVMRelocROPI; }
LLVM_API int RelocRWPI() { return LLVMRelocRWPI; }
LLVM_API int RelocROPI_RWPI() { return LLVMRelocROPI_RWPI; }
LLVM_API int CodeModelDefault() { return LLVMCodeModelDefault; }
LLVM_API int CodeModelJITDefault() { return LLVMCodeModelJITDefault; }
LLVM_API int CodeModelTiny() { return LLVMCodeModelTiny; }
LLVM_API int CodeModelSmall() { return LLVMCodeModelSmall; }
LLVM_API int CodeModelKernel() { return LLVMCodeModelKernel; }
LLVM_API int CodeModelMedium() { return LLVMCodeModelMedium; }
LLVM_API int CodeModelLarge() { return LLVMCodeModelLarge; }
LLVM_API int AssemblyFile() { return LLVMAssemblyFile; }
LLVM_API int ObjectFile() { return LLVMObjectFile; }
